pub const CAPTCHA_QUOTES: &[&str] = &[
    "Buktikan kamu manusia, bukan robot.",
    "Satu langkah lagi, selesaikan CAPTCHA ini.",
    "CAPTCHA dulu, akses penuh menyusul.",
    "Jawaban tepat, pintu terbuka.",
    "Bentar, cek manusia dulu ya.",
    "Cuma sebentar, bantu verifikasi.",
    "Klik jawaban yang benar untuk lanjut.",
    "Yuk, selesaikan tantangan ini.",
    "Aman dulu, baru masuk.",
    "Tunjukkan kamu bukan bot.",
    "Selesaikan CAPTCHA agar bisa masuk.",
    "Pilih jawaban yang benar untuk lanjut.",
    "Uji cepat, akses siap menunggu.",
    "Sedikit lagi, tinggal CAPTCHA.",
    "Ikuti tantangan, lalu masuk.",
    "Verifikasi dulu, baru gabung.",
    "Cek singkat, lanjut aktivitas.",
    "Buktikan dirimu, lanjutkan.",
    "Tantangan kecil sebelum masuk.",
    "Jawaban benar, akses dibuka.",
    "Pastikan kamu manusia dulu ya.",
    "Selesaikan tes ini untuk lanjut.",
    "Kamu hampir masuk, tinggal CAPTCHA.",
    "Pilih opsi yang tepat.",
    "Jawaban benar, akses group menunggu.",
    "Tunjukkan kamu manusia, bukan bot.",
    "Verifikasi singkat untuk keamanan.",
    "CAPTCHA singkat, akses mantap.",
    "Sedikit usaha, akses terbuka.",
    "Satu klik benar, jalan terus.",
    "Mohon verifikasi untuk melanjutkan akses.",
    "Verifikasi keamanan: selesaikan CAPTCHA.",
    "Validasi singkat demi keamanan grup.",
    "Harap selesaikan CAPTCHA sebelum bergabung.",
    "Akses diberikan setelah verifikasi berhasil.",
    "Selesaikan tantangan ini untuk membuka akses.",
    "Langkah verifikasi sederhana sebelum masuk.",
    "Pastikan verifikasi selesai agar akses aktif.",
    "Cek identitas singkat, lalu lanjut.",
    "Verifikasi cepat, akses segera dibuka.",
    "Silakan buktikan bahwa kamu manusia.",
    "Selesaikan CAPTCHA untuk melanjutkan.",
    "Hampir selesai, tinggal verifikasi.",
    "Sedikit tantangan, akses menanti.",
    "Jawab benar, akses resmi dibuka.",
    "Silakan pilih jawaban yang tepat.",
    "Verifikasi sebentar ya, biar aman.",
    "Satu tantangan lagi sebelum masuk.",
    "Jawabanmu menentukan akses berikutnya.",
    "Buktikan kamu manusia, pintu terbuka.",
    "Sedikit tes, akses penuh menunggu.",
    "Tunjukkan respon yang benar untuk masuk.",
    "Jawab dengan benar agar akses aktif.",
    "Verifikasi ini demi keamanan bersama.",
    "Selesaikan CAPTCHA agar bisa lanjut.",
    "Cuma sebentar, akses siap.",
    "Aman dulu, akses kemudian.",
    "Tuntaskan CAPTCHA, akses terbuka.",
    "Kalibrasi manusia: pilih jawaban benar.",
    "Tes cepat: manusia atau bot?",
    "CAPTCHA dulu, baru nongkrong.",
    "Pilih jawaban benar, baru kita lanjut.",
    "Bentar ya, bot-check dulu.",
    "Pilih yang bener, kita gas.",
    "Satu klik benar, akses meluncur.",
    "Ayo buktikan kamu manusia.",
    "Tes singkat, akses mantap.",
    "Sedikit soal, akses total.",
    "Captcha kecil, hasil besar.",
    "Tunjukkan skill klikmu.",
    "Jangan panik, pilih yang tepat.",
    "Biar aman, jawab dulu.",
    "Jawab benar, kita lanjut.",
    "Manusia? Buktikan dengan CAPTCHA.",
    "Senyum dulu, lalu jawab.",
    "Tantangan mini sebelum gabung.",
    "Tes kecil, akses besar.",
    "Serius dikit, lalu santai.",
    "Langkah aman, akses nyaman.",
    "CAPTCHA selesai, akses beres.",
    "Buktikan cepat, masuk tepat.",
    "Jawab ini, akses jadi milikmu.",
    "Jangan gagal, akses menunggu.",
    "Sedikit fokus, lalu masuk.",
    "Biar aman, verifikasi dulu.",
    "Klik benar, akses segera.",
    "Tes kilat, akses kilat.",
    "Satu jawaban, banyak manfaat.",
    "Captcha dulu, ngobrol kemudian.",
    "Selesaikan ini, akses aman.",
    "Jangan asal, pilih yang benar.",
    "Tunjukkan kamu manusia, kita lanjut.",
    "Buktikan dulu, baru gabung.",
    "Ayok, selesaikan CAPTCHA.",
    "Tes kecil, keamanan besar.",
    "Satu langkah, akses penuh.",
    "Pilih benar, pintu terbuka.",
    "Sedikit sabar, akses besar.",
    "Ayo, buktikan bukan bot.",
    "Pastikan jawabannya tepat.",
    "Klik yang benar ya.",
    "Verifikasi cepat, lanjut cepat.",
    "Tantangan ringan, akses nyaman.",
    "CAPTCHA cepat, akses rapat.",
    "Cek cepat, lanjut rapat.",
    "Bentar lagi, akses full.",
    "Jawab ini, akses unlocked.",
    "Selesaikan CAPTCHA, akses unlocked.",
    "Jangan khawatir, cuma sebentar.",
    "Pilih benar, akses aman.",
    "Jangan menyerah, tinggal satu.",
    "Uji manusia, akses dibuka.",
    "Yuk buktikan, lanjut masuk.",
    "Pilih opsi tepat, lanjut.",
    "Jawab tepat, akses cepat.",
    "Verifikasi singkat, aman lanjut.",
    "Satu tantangan, banyak akses.",
    "Buktikan kamu manusia, dan masuk.",
    "CAPTCHA ini cuma sebentar kok.",
    "Kita cek dulu ya, sebentar.",
    "Klik yang tepat, akses terbuka.",
    "Tes singkat, akses langsung.",
    "Selesaikan tes ini, lanjut.",
    "Biar rapi, verifikasi dulu.",
    "Biar aman, cek cepat.",
    "Satu langkah lagi, akses penuh.",
    "Selesaikan dulu, lalu gabung.",
    "Tes singkat, akses mantap.",
    "Captcha sebentar, akses selamanya.",
    "Buktikan dulu, baru seru-seruan.",
    "Serius sebentar, santai selamanya.",
    "Pilih jawaban benar, gas.",
    "Tes kecil, masuk besar.",
    "Tantangan mini, akses maxi.",
    "Jawab benar, akses maknyus.",
    "Buktikan kamu manusia, gaskeun.",
    "Captcha kecil, lanjut besar.",
    "Tes cepat, masuk cepat.",
    "Sedikit tantangan, banyak manfaat.",
    "Buktikan kamu manusia, aman bersama.",
    "Validasi cepat, lanjutkan.",
    "Satu tes lagi, akses penuh.",
    "Cek cepat, akses mantap.",
    "Tantangan kecil, akses besar.",
    "Selesaikan ini, lanjutkan.",
    "Klik yang benar, lanjutkan.",
    "Tunjukkan jawaban yang tepat.",
    "Jawab dengan benar, akses terbuka.",
    "Captcha selesai, akses terbuka.",
    "CAPTCHA ini cepat kok.",
    "Sedikit tes, lanjut.",
    "Pilih jawaban benar, masuk.",
    "Verifikasi dan lanjut masuk.",
    "CAPTCHA kecil, lanjut besar.",
    "Cek singkat, akses besar.",
    "Tuntaskan ini, lanjut.",
    "Satu langkah aman, akses nyaman.",
    "Jawaban tepat, akses mantap.",
    "Verifikasi dulu ya, aman.",
    "Tunjukkan kamu manusia, yuk.",
    "Buktikan kamu manusia sekarang.",
    "Biar aman, ayo verifikasi.",
    "Buktikan, lalu masuk.",
    "Menjawab dengan benar, kamu akan mendapatkan akses group",
];
